name: SaveBlockStats
main: com.MrEngMan.SaveBlockStats.Main
author: MrEngMan
description: Count how many time blockes were placed and broken by players in each chunk
api-version: '1.13'
version: 1.0

commands:
  sbsreload:
    description: Reload Config
    usage: '/sbsreload'

permissions:
  sbs.reload:
    default: op

